/**
 *    Copyright (C) 2025 EloqData Inc.
 *
 *    This program is free software: you can redistribute it and/or  modify
 *    it under either of the following two licenses:
 *    1. GNU Affero General Public License, version 3, as published by the Free
 *    Software Foundation.
 *    2. GNU General Public License as published by the Free Software
 *    Foundation; version 2 of the License.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License or GNU General Public License for more
 *    details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    and GNU General Public License V2 along with this program.  If not, see
 *    <http://www.gnu.org/licenses/>.
 *
 */
#include "cc/cc_request.h"

#include <atomic>
#include <cassert>

namespace txservice
{
void ReplayLogCc::SetFinish()
{
    // Notifies the external caller--the log replay handler--that the
    // specified log record has been replayed in all cores of this node.
    // HandlerResult is not used by external caller, hence we don't need to
    // call HandlerResult.SetFinished().
    if (local_on_fly_cnt_ == nullptr ||
        local_on_fly_cnt_->fetch_sub(1, std::memory_order_relaxed) == 1)
    {
        // local_on_fly_cnt_ is nullptr means it's not a data log.
        // Otherwise, it's a data log generated by ParseDataLogCc,
        // only one of them can reach here.
        delete local_on_fly_cnt_;
        external_on_fly_cnt_->fetch_sub(1, std::memory_order_relaxed);

        if (parse_cc_ != nullptr)
        {
            // ParseDataLogCc is the owner of the ReplayMessage, so should
            // release the memory used by the ReplayMessage
            parse_cc_->OnFinish();
        }
    }
}

void ReplayLogCc::AbortCcRequest(CcErrorCode err_code)
{
    assert(err_code != CcErrorCode::NO_ERROR);

    {
        BAIDU_SCOPED_LOCK(*external_mux_);
        *recovery_error_ = true;
    }
    if (local_on_fly_cnt_ == nullptr ||
        local_on_fly_cnt_->fetch_sub(1, std::memory_order_relaxed) == 1)
    {
        // local_on_fly_cnt_ is nullptr means it's not a data log.
        // Otherwise, it's a data log generated by ParseDataLogCc,
        // only one of them can reach here.
        delete local_on_fly_cnt_;
        external_on_fly_cnt_->fetch_sub(1, std::memory_order_relaxed);

        if (parse_cc_ != nullptr)
        {
            // ParseDataLogCc is the owner of the ReplayMessage, so should
            // release the memory used by the ReplayMessage
            parse_cc_->OnFinish();
        }
    }
}

void CkptTsCc::Wait()
{
    uint64_t interval_us = 100;
    constexpr uint64_t max_interval = 100000;
    while (unfinish_cnt_.load(std::memory_order_acquire) > 0)
    {
        bthread_usleep(interval_us);
        if ((interval_us << 1) < max_interval)
            interval_us <<= 1;
    }
}

void ClearTxCc::Wait()
{
    uint64_t interval_us = 100;
    constexpr uint64_t max_interval = 100000;
    while (finish_cnt_.load(std::memory_order_acquire) < core_cnt_)
    {
        bthread_usleep(interval_us);
        if ((interval_us << 1) < max_interval)
            interval_us <<= 1;
    }
}

void ActiveTxMaxTsCc::Wait()
{
    uint64_t interval_us = 100;
    constexpr uint64_t max_interval = 100000;
    while (unfinish_cnt_.load(std::memory_order_acquire) > 0)
    {
        bthread_usleep(interval_us);
        if ((interval_us << 1) < max_interval)
            interval_us <<= 1;
    }
}

void EscalateStandbyCcmCc::Wait()
{
    uint64_t interval_us = 100;
    constexpr uint64_t max_interval = 100000;
    while (unfinished_cnt_.load(std::memory_order_acquire) > 0)
    {
        bthread_usleep(interval_us);
        if ((interval_us << 1) < max_interval)
            interval_us <<= 1;
    }
}

void DbSizeCc::Wait()
{
    // Wait for all local cores and remote node groups to report. After
    // roughly 2 seconds, if only remote responses are missing, give up on
    // them; a late response of the same term is dropped by the term check
    // in AddRemoteObjSize().
    constexpr uint64_t max_wait_us = 2000000;
    uint64_t waited_us = 0;
    uint64_t interval_us = 100;
    constexpr uint64_t max_interval = 100000;
    while (total_ref_cnt_.load(std::memory_order_acquire) > 0)
    {
        if (waited_us >= max_wait_us &&
            total_ref_cnt_.load(std::memory_order_acquire) <=
                remote_ref_cnt_.load(std::memory_order_acquire))
        {
            LOG(WARNING) << "Waitting timeout for dbsize";
            break;
        }
        bthread_usleep(interval_us);
        waited_us += interval_us;
        if ((interval_us << 1) < max_interval)
            interval_us <<= 1;
    }
}
}  // namespace txservice
