/**
 *    Copyright (C) 2025 EloqData Inc.
 *
 *    This program is free software: you can redistribute it and/or  modify
 *    it under either of the following two licenses:
 *    1. GNU Affero General Public License, version 3, as published by the Free
 *    Software Foundation.
 *    2. GNU General Public License as published by the Free Software
 *    Foundation; version 2 of the License.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Affero General Public License or GNU General Public License for more
 *    details.
 *
 *    You should have received a copy of the GNU Affero General Public License
 *    and GNU General Public License V2 along with this program.  If not, see
 *    <http://www.gnu.org/licenses/>.
 *
 */
#include "cc/cc_request.h"

#include <atomic>
#include <cassert>

namespace txservice
{
void ReplayLogCc::SetFinish()
{
    // Notifies the external caller--the log replay handler--that the
    // specified log record has been replayed in all cores of this node.
    // HandlerResult is not used by external caller, hence we don't need to
    // call HandlerResult.SetFinished().
    if (local_on_fly_cnt_ == nullptr ||
        local_on_fly_cnt_->fetch_sub(1, std::memory_order_relaxed) == 1)
    {
        // local_on_fly_cnt_ is nullptr means it's not a data log.
        // Otherwise, it's a data log generated by ParseDataLogCc,
        // only one of them can reach here.
        delete local_on_fly_cnt_;
        external_on_fly_cnt_->fetch_sub(1, std::memory_order_relaxed);

        if (parse_cc_ != nullptr)
        {
            // ParseDataLogCc is the owner of the ReplayMessage, so should
            // release the memory used by the ReplayMessage
            parse_cc_->OnFinish();
        }
    }
}

void ReplayLogCc::AbortCcRequest(CcErrorCode err_code)
{
    assert(err_code != CcErrorCode::NO_ERROR);

    {
        BAIDU_SCOPED_LOCK(*external_mux_);
        *recovery_error_ = true;
    }
    if (local_on_fly_cnt_ == nullptr ||
        local_on_fly_cnt_->fetch_sub(1, std::memory_order_relaxed) == 1)
    {
        // local_on_fly_cnt_ is nullptr means it's not a data log.
        // Otherwise, it's a data log generated by ParseDataLogCc,
        // only one of them can reach here.
        delete local_on_fly_cnt_;
        external_on_fly_cnt_->fetch_sub(1, std::memory_order_relaxed);

        if (parse_cc_ != nullptr)
        {
            // ParseDataLogCc is the owner of the ReplayMessage, so should
            // release the memory used by the ReplayMessage
            parse_cc_->OnFinish();
        }
    }
}

}  // namespace txservice